[package]
name = "limited-core"
description = "AST, types, and expressions for the Limited Shell language"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# pest = { workspace = true }
# pest_derive = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bstr = { workspace = true }
petgraph = { workspace = true }
regex = "1"
